"use client";

import { ArrowRight, Bug, CalendarDays, CheckCircle2, Droplets, Image, ListChecks, MoreHorizontal, Plus, Search, Sprout } from "lucide-react";
import { useState } from "react";

const activityItems = [
  { type: "Care", icon: Droplets, title: "Checked soil moisture", subject: "Cherry tomato · Patio", detail: "Soil felt slightly damp. No watering needed.", time: "Today, 8:42 AM" },
  { type: "Observation", icon: Bug, title: "Leaf holes observed", subject: "Kale & lettuce · Raised bed", detail: "A few new holes on two outer leaves. Monitoring for caterpillars.", time: "Saturday, 10:18 AM" },
  { type: "Photo", icon: Image, title: "Progress photo added", subject: "Hydrangea · Back border", detail: "Flowering well after last week’s warm weather.", time: "Friday, 6:30 PM" },
  { type: "Care", icon: Droplets, title: "Watered herb pots", subject: "Herb pots · Patio", detail: "Completed from Garden Walk.", time: "Wednesday, 7:55 AM" },
  { type: "Observation", icon: CheckCircle2, title: "Garden Walk completed", subject: "Whole garden", detail: "Five plantings checked; nothing urgent found.", time: "Wednesday, 7:59 AM" },
];

export function ActivityScreen({ fresh = false }: { fresh?: boolean }) {
  const [filter, setFilter] = useState("All");
  const visible = filter === "All" ? activityItems : activityItems.filter((item) => item.type === filter);
  if (fresh) return <div className="screen activity-screen starter-activity"><header className="section-header"><div><span className="eyebrow">Garden history</span><h1>Activity</h1><p>Care, observations, photos, and completed walks will collect here.</p></div><button className="secondary-button"><Plus size={17} /> Add note</button></header><section className="first-activity-card"><div className="timeline-date"><CalendarDays size={15} /> Today</div><article className="activity-item"><span className="activity-icon"><Sprout size={18} /></span><div className="activity-content"><span className="activity-type">Garden setup</span><h2>Garden nasturtium added</h2><p className="activity-subject">Patio pots</p><p>Your first planting was identified and confirmed.</p><time>Just now</time></div></article></section><section className="activity-empty-help"><ListChecks size={26} /><div><h2>Your history will build itself</h2><p>Completing care, checking a plant, or adding a progress photo creates Activity without making you keep a manual journal.</p></div></section></div>;
  return <div className="screen activity-screen"><header className="section-header"><div><span className="eyebrow">Garden history</span><h1>Activity</h1><p>Care, observations, photos, and completed walks—recorded without extra paperwork.</p></div><button className="secondary-button"><Plus size={17} /> Add note</button></header><div className="activity-toolbar"><div className="activity-filters">{["All", "Care", "Observation", "Photo"].map((item) => <button className={filter === item ? "is-active" : ""} key={item} onClick={() => setFilter(item)}>{item === "All" ? "All activity" : item}</button>)}</div><label className="activity-search"><Search size={16} /><input aria-label="Search garden activity" placeholder="Search activity" /></label></div><div className="activity-layout"><section className="timeline" aria-label="Garden activity timeline"><div className="timeline-date"><CalendarDays size={15} /> This week</div>{visible.map((item, index) => { const Icon = item.icon; return <article className="activity-item" key={`${item.title}-${index}`}><span className={`activity-icon type-${item.type.toLowerCase()}`}><Icon size={18} /></span><div className="activity-content"><span className="activity-type">{item.type}</span><h2>{item.title}</h2><p className="activity-subject">{item.subject}</p><p>{item.detail}</p><time>{item.time}</time></div><button className="icon-button" aria-label={`More options for ${item.title}`}><MoreHorizontal size={18} /></button></article>; })}</section><aside className="activity-aside"><span className="eyebrow">This month</span><h2>Your garden at a glance</h2><div className="activity-stat"><strong>4</strong><span>Garden Walks</span></div><div className="activity-stat"><strong>9</strong><span>Care actions</span></div><div className="activity-stat"><strong>5</strong><span>Progress photos</span></div><button className="text-button dark">Compare plant progress <ArrowRight size={16} /></button></aside></div></div>;
}
