"use client";

import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronRight, CloudRain, Flower2, Leaf, MoreHorizontal, Plus, ScanLine, Search, Sprout, SunMedium, Upload, Bug } from "lucide-react";
import { useState } from "react";
import { gardenAreas } from "./fixtures";

export function GardenScreen({ onAddPlant, onAsk, fresh = false }: { onAddPlant: () => void; onAsk: (context: string) => void; fresh?: boolean }) {
  const [selectedArea, setSelectedArea] = useState("All areas");
  const visibleAreas = selectedArea === "All areas" ? gardenAreas : gardenAreas.filter((area) => area.name === selectedArea);
  if (fresh) return <div className="screen garden-screen starter-garden"><header className="section-header"><div><span className="eyebrow">My first garden</span><h1>One planting, one place</h1><p>Start small. Add the rest as you spend time in the garden.</p></div><button className="primary-button" onClick={onAddPlant}><Plus size={18} /> Add planting</button></header><section className="garden-overview fresh-overview"><div><span className="summary-icon"><Sprout size={19} /></span><p><strong>1 planting</strong><small>Enough for first advice</small></p></div><div><span className="summary-icon"><CheckCircle2 size={19} /></span><p><strong>Doing well</strong><small>No urgent care today</small></p></div><div><span className="summary-icon"><SunMedium size={19} /></span><p><strong>Mostly sunny</strong><small>Patio pots</small></p></div></section><div className="area-card-grid single-area"><article className="garden-area-card"><header><div className="area-illustration"><Leaf size={26} /></div><div className="area-title"><span>Containers</span><h2>Patio pots</h2><p><SunMedium size={13} /> Mostly sunny</p></div><button className="icon-button"><MoreHorizontal size={19} /></button></header><div className="area-note"><SunMedium size={16} /><span>Check containers during warm weather</span></div><div className="planting-list"><button className="planting-row" onClick={() => onAsk("Garden nasturtium · Patio pots")}><span className="planting-avatar"><Flower2 size={18} /></span><span><strong>Garden nasturtium</strong><small>One container · Established</small></span><span className="plant-status good">Doing well</span><ChevronRight size={17} /></button></div><button className="area-add" onClick={onAddPlant}><Plus size={15} /> Add to Patio pots</button></article><button className="add-area-card"><Plus size={22} /><strong>Create another garden area</strong><span>Raised bed, border, or another group of containers</span></button></div></div>;
  return <div className="screen garden-screen"><header className="section-header"><div><span className="eyebrow">My garden</span><h1>Six plantings, three places</h1><p>Organized by where things grow—not by complicated garden records.</p></div><button className="primary-button" onClick={onAddPlant}><Plus size={18} /> Add planting</button></header><div className="garden-toolbar"><div className="area-tabs" role="tablist" aria-label="Filter garden areas">{["All areas", ...gardenAreas.map((area) => area.name)].map((area) => <button className={selectedArea === area ? "is-active" : ""} key={area} onClick={() => setSelectedArea(area)}>{area}</button>)}</div><button className="secondary-button"><Search size={16} /> Find a planting</button></div><section className="garden-overview" aria-label="Garden summary"><div><span className="summary-icon"><Sprout size={19} /></span><p><strong>6 plantings</strong><small>Across mixed growing spaces</small></p></div><div><span className="summary-icon"><CheckCircle2 size={19} /></span><p><strong>4 doing well</strong><small>No care needed today</small></p></div><div><span className="summary-icon amber"><Bug size={19} /></span><p><strong>1 follow-up</strong><small>Kale leaf holes</small></p></div></section><div className="area-card-grid">{visibleAreas.map((area) => <article className="garden-area-card" key={area.name}><header><div className="area-illustration"><Leaf size={26} /></div><div className="area-title"><span>{area.type}</span><h2>{area.name}</h2><p><SunMedium size={13} /> {area.light}</p></div><button className="icon-button" aria-label={`More options for ${area.name}`}><MoreHorizontal size={19} /></button></header><div className="area-note"><CloudRain size={16} /><span>{area.note}</span></div><div className="planting-list">{area.plants.map((plant) => <button className="planting-row" key={plant.name} onClick={() => onAsk(`${plant.name} · ${area.name}`)}><span className="planting-avatar"><Flower2 size={18} /></span><span><strong>{plant.name}</strong><small>{plant.detail}</small></span><span className={`plant-status ${plant.tone}`}>{plant.status}</span><ChevronRight size={17} /></button>)}</div><button className="area-add" onClick={onAddPlant}><Plus size={15} /> Add to {area.name}</button></article>)}</div></div>;
}

export function AddPlantScreen({ onBack, onDone }: { onBack: () => void; onDone: () => void }) {
  const [step, setStep] = useState(0); const [method, setMethod] = useState("photo"); const [plantName, setPlantName] = useState("");
  return <div className="screen add-plant-screen"><button className="back-button" onClick={step === 0 ? onBack : () => setStep(step - 1)}><ArrowLeft size={18} /> {step === 0 ? "Garden" : "Back"}</button><div className="setup-progress"><span style={{ width: `${Math.max(18, (step + 1) * 25)}%` }} /></div>
    {step === 0 && <section className="setup-panel"><span className="eyebrow">Add a planting</span><h1>What are you growing?</h1><p>Start with a photo or a name. You only need enough detail to make the first advice useful.</p><div className="method-grid"><button className={method === "photo" ? "is-active" : ""} onClick={() => setMethod("photo")}><Camera size={25} /><span><strong>Take a plant photo</strong><small>Best when you are beside it</small></span></button><button className={method === "label" ? "is-active" : ""} onClick={() => setMethod("label")}><ScanLine size={25} /><span><strong>Photograph a label</strong><small>Plant tag or seed packet</small></span></button><button className={method === "search" ? "is-active" : ""} onClick={() => setMethod("search")}><Search size={25} /><span><strong>Search by name</strong><small>Common names work well</small></span></button></div>{method === "search" ? <label className="search-field"><Search size={18} /><input value={plantName} onChange={(event) => setPlantName(event.target.value)} placeholder="Try ‘nasturtium’" autoFocus /></label> : <label className="upload-zone"><Upload size={23} /><span><strong>Choose a photo to continue</strong><small>Clear daylight photos work best</small></span><input type="file" accept="image/*" onChange={() => setStep(1)} /></label>}<button className="primary-button setup-next" disabled={method === "search" && !plantName.trim()} onClick={() => setStep(1)}>Continue <ArrowRight size={18} /></button></section>}
    {step === 1 && <section className="setup-panel identification-panel"><span className="eyebrow">Possible identification</span><h1>This looks like a nasturtium.</h1><p>Check the round leaves and radiating veins before adding it to your garden.</p><article className="identification-result"><div className="identified-image"><Flower2 size={52} /></div><div><span className="confidence">Likely match</span><h2>Garden nasturtium</h2><p><em>Tropaeolum majus</em> · Edible flowering annual</p><button className="text-button dark">See two other possibilities <ChevronRight size={16} /></button></div><CheckCircle2 size={24} /></article><div className="identification-actions"><button className="primary-button" onClick={() => setStep(2)}>Yes, this is my plant</button><button className="secondary-button">Take another photo</button><button className="secondary-button">Choose a different plant</button></div></section>}
    {step === 2 && <section className="setup-panel details-panel"><span className="eyebrow">Planting details</span><h1>Add a little context</h1><p>These basics help Verdant tailor care. You can fill in anything else later.</p><div className="field-grid"><label><span>Where is it growing?</span><select defaultValue="Patio"><option>Patio</option><option>Raised bed</option><option>Back border</option></select></label><label><span>What does this record represent?</span><select defaultValue="One container"><option>One plant</option><option>One container</option><option>A row or patch</option></select></label><label><span>Growth stage</span><select defaultValue="Established"><option>Young</option><option>Established</option><option>Flowering</option><option>Producing</option><option>Not sure</option></select></label><label><span>How does it look?</span><select defaultValue="Looks healthy"><option>Looks healthy</option><option>Something seems wrong</option><option>Not sure</option></select></label></div><label className="optional-field"><span>Nickname <small>Optional</small></span><input placeholder="For example, porch nasturtium" /></label><div className="setup-actions"><button className="primary-button" onClick={() => setStep(3)}>Save planting</button><button className="secondary-button" onClick={onBack}>Cancel</button></div></section>}
    {step === 3 && <section className="setup-panel success-panel"><div className="summary-check"><Check size={33} /></div><span className="eyebrow">Planting added</span><h1>Your nasturtium is ready.</h1><p>It will appear in Patio and can be included in future Garden Walks.</p><div className="first-advice"><SunMedium size={21} /><div><strong>A useful first check</strong><p>Nasturtiums flower best with plenty of light, but patio containers may need a moisture check during warm weather.</p></div></div><div className="summary-actions"><button className="primary-button" onClick={onDone}>View Garden</button><button className="secondary-button" onClick={() => setStep(0)}>Add another</button></div></section>}
  </div>;
}
