"use client";

import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronRight, Flower2, Leaf, MapPin, ScanLine, Search, Sparkles, Sprout, SunMedium } from "lucide-react";
import { useState } from "react";
import { Logo } from "./navigation";

export function FreshWelcomeScreen({ onStart }: { onStart: () => void }) {
  return <div className="screen welcome-screen">
    <header className="welcome-topbar"><Logo /><span>Beginner-friendly garden coaching</span></header>
    <main className="welcome-layout">
      <section className="welcome-copy"><span className="eyebrow"><Sparkles size={15} /> Welcome to Verdant</span><h1>Start with one spot.<br />We’ll learn the rest together.</h1><p>Tell us where you garden, add one planting, and get your first useful check. No garden map or expert knowledge required.</p><div className="welcome-actions"><button className="primary-button large" onClick={onStart}>Set up my garden <ArrowRight size={18} /></button><span>About 3 minutes</span></div><div className="welcome-assurances"><span><Check size={16} /> Start with one plant</span><span><Check size={16} /> Change anything later</span><span><Check size={16} /> Advice in plain language</span></div></section>
      <aside className="setup-preview-card"><div className="setup-preview-head"><span>Your first garden</span><small>0 of 3 complete</small></div><div className="preview-step is-next"><span>1</span><div><strong>Set your location</strong><small>For weather and seasonal timing</small></div><ChevronRight size={18} /></div><div className="preview-step"><span>2</span><div><strong>Create one garden area</strong><small>Patio, raised bed, or border</small></div></div><div className="preview-step"><span>3</span><div><strong>Add your first planting</strong><small>Use a photo, label, or name</small></div></div><div className="preview-outcome"><Leaf size={20} /><div><strong>Then Verdant gets useful</strong><p>You’ll receive a first check based on the plant, its growing space, and local conditions.</p></div></div></aside>
    </main>
  </div>;
}

export function FirstGardenSetup({ onBack, onComplete }: { onBack: () => void; onComplete: () => void }) {
  const [step, setStep] = useState(0);
  const [location, setLocation] = useState("");
  const [areaType, setAreaType] = useState("Containers");
  const [areaName, setAreaName] = useState("Patio pots");
  const [sunlight, setSunlight] = useState("Mostly sunny");
  const [plantMethod, setPlantMethod] = useState("photo");
  const [plantSearch, setPlantSearch] = useState("");
  return <div className="screen first-setup-screen">
    <header className="setup-header"><button className="back-button" onClick={step === 0 ? onBack : () => setStep(step - 1)}><ArrowLeft size={18} /> {step === 0 ? "Welcome" : "Back"}</button><span>Step {Math.min(step + 1, 4)} of 4</span><button className="setup-exit" onClick={onBack}>Finish later</button></header>
    <div className="setup-progress segmented" aria-label={`Step ${Math.min(step + 1, 4)} of 4`}>{[0, 1, 2, 3].map((item) => <span className={item <= step ? "is-complete" : ""} key={item} />)}</div>
    {step === 0 && <section className="setup-panel location-step"><div className="setup-step-icon"><MapPin size={26} /></div><span className="eyebrow">Local guidance</span><h1>Where is your garden?</h1><p>Your city is enough to account for rain, heat, frost, and seasonal timing. Verdant doesn’t need continuous location access.</p><label className="location-field"><span>City or postal code</span><div><MapPin size={18} /><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Enter your city" autoFocus /></div></label><div className="or-divider"><span>or</span></div><button className="location-button" onClick={() => setLocation("Toronto, ON")}><MapPin size={18} /><span><strong>Use my current location</strong><small>Only while setting up this garden</small></span></button><button className="primary-button setup-next" disabled={!location} onClick={() => setStep(1)}>Continue <ArrowRight size={18} /></button></section>}
    {step === 1 && <section className="setup-panel"><span className="eyebrow">Your first area</span><h1>Where should we start?</h1><p>Add just one place for now. You can create the rest of your garden after seeing the first useful advice.</p><div className="method-grid area-methods">{[{ name: "Containers", detail: "Pots, planters, or grow bags", icon: Sprout }, { name: "Raised bed", detail: "One contained growing bed", icon: Leaf }, { name: "In-ground", detail: "A bed, border, or garden patch", icon: Flower2 }].map((item) => { const Icon = item.icon; return <button className={areaType === item.name ? "is-active" : ""} key={item.name} onClick={() => { setAreaType(item.name); setAreaName(item.name === "Containers" ? "Patio pots" : item.name === "Raised bed" ? "Vegetable bed" : "Back border"); }}><Icon size={25} /><span><strong>{item.name}</strong><small>{item.detail}</small></span></button>; })}</div><div className="field-grid setup-fields"><label><span>Give this area a simple name</span><input value={areaName} onChange={(event) => setAreaName(event.target.value)} /></label><label><span>Approximately how much sun?</span><select value={sunlight} onChange={(event) => setSunlight(event.target.value)}><option>Mostly sunny</option><option>Partly sunny</option><option>Mostly shaded</option><option>Not sure</option></select></label></div><button className="primary-button setup-next" disabled={!areaName.trim()} onClick={() => setStep(2)}>Create this area <ArrowRight size={18} /></button></section>}
    {step === 2 && <section className="setup-panel"><span className="eyebrow">Your first planting</span><h1>What’s growing in {areaName}?</h1><p>One plant is enough to begin. If you’re not sure what it is, a photo can help Verdant suggest a match.</p><div className="method-grid"><button className={plantMethod === "photo" ? "is-active" : ""} onClick={() => setPlantMethod("photo")}><Camera size={25} /><span><strong>Take a plant photo</strong><small>Best when you’re beside it</small></span></button><button className={plantMethod === "label" ? "is-active" : ""} onClick={() => setPlantMethod("label")}><ScanLine size={25} /><span><strong>Photograph a label</strong><small>Plant tag or seed packet</small></span></button><button className={plantMethod === "search" ? "is-active" : ""} onClick={() => setPlantMethod("search")}><Search size={25} /><span><strong>Search by name</strong><small>Common names work well</small></span></button></div>{plantMethod === "search" ? <label className="search-field"><Search size={18} /><input value={plantSearch} onChange={(event) => setPlantSearch(event.target.value)} placeholder="Try ‘nasturtium’" autoFocus /></label> : <button className="demo-photo-button" onClick={() => setStep(3)}><Camera size={22} /><span><strong>Take or choose a photo</strong><small>For this prototype, continue to see an example match</small></span><ChevronRight size={18} /></button>}<button className="primary-button setup-next" disabled={plantMethod === "search" && !plantSearch.trim()} onClick={() => setStep(3)}>Continue <ArrowRight size={18} /></button></section>}
    {step === 3 && <section className="setup-panel first-match-panel"><span className="eyebrow">Confirm your first plant</span><h1>This looks like a nasturtium.</h1><p>Verdant found a likely match. Confirm it before anything is added to your garden.</p><article className="identification-result first-result"><div className="identified-image"><Flower2 size={52} /></div><div><span className="confidence">Likely match</span><h2>Garden nasturtium</h2><p><em>Tropaeolum majus</em> · Edible flowering annual</p><div className="match-context"><MapPin size={13} /> {areaName} · {areaType} · {sunlight}</div></div><CheckCircle2 size={24} /></article><div className="first-check-preview"><SunMedium size={20} /><div><strong>Your first useful check</strong><p>Because this is in a sunny container, start by checking its soil during warm weather rather than watering on a fixed schedule.</p></div></div><div className="setup-actions"><button className="primary-button" onClick={onComplete}>Confirm and add plant</button><button className="secondary-button" onClick={() => setStep(2)}>This isn’t the right plant</button></div></section>}
  </div>;
}
