"use client";

import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronRight, CircleHelp, CloudRain, Flower2, ListChecks, MapPin, Pause, Sparkles } from "lucide-react";
import { useState } from "react";
import type { WalkItem } from "./types";

export function WalkOverview({ items, onBack, onStart, onSkip }: { items: WalkItem[]; onBack: () => void; onStart: (index?: number) => void; onSkip: (id: number) => void }) {
  const areas = Array.from(new Set(items.map((item) => item.area)));
  const checked = items.filter((item) => item.status === "good").length;
  return <div className="screen walk-screen">
    <button className="back-button" onClick={onBack}><ArrowLeft size={18} /> Today</button><header className="walk-header"><div><span className="eyebrow">Garden Walk</span><h1>Your route for today</h1><p>Four quick checks, grouped by location. Skip anything that isn’t convenient.</p></div><div className="walk-time"><strong>6</strong><span>minutes<br />estimated</span></div></header><div className="progress-track" aria-label={`${checked} of ${items.length} checks complete`}><span style={{ width: `${Math.max((checked / items.length) * 100, 3)}%` }} /></div>
    <div className="overview-layout"><div className="route-list">{areas.map((area, areaIndex) => <section className="area-group" key={area}><div className="area-heading"><span className="area-number">{String(areaIndex + 1).padStart(2, "0")}</span><div><h2>{area}</h2><p>{items.filter((item) => item.area === area).length} checks</p></div></div><div className="area-items">{items.map((item, itemIndex) => item.area === area && <article className={`route-item status-${item.status}`} key={item.id}><button className="route-main" onClick={() => onStart(itemIndex)}><span className="route-status">{item.status === "good" ? <Check size={17} /> : item.status === "skipped" ? "–" : item.id}</span><span><strong>{item.name}</strong><small>{item.place} · {item.meta}</small></span><ChevronRight size={18} /></button><button className="skip-button" onClick={() => onSkip(item.id)}>{item.status === "skipped" ? "Restore" : "Skip"}</button></article>)}</div></section>)}</div><aside className="route-aside"><span className="eyebrow">Why this route?</span><h2>Start with the patio.</h2><p>Containers dry sooner than beds, and the temperature will rise before afternoon rain.</p><div className="weather-note"><CloudRain size={19} /><span><strong>Rain likely after 4 PM</strong><small>Raised bed watering isn’t included.</small></span></div><button className="primary-button full" onClick={() => onStart()}>Start walk <ArrowRight size={18} /></button></aside></div>
  </div>;
}

export function WalkGuide({ item, index, total, onOverview, onPause, onAnswer }: { item: WalkItem; index: number; total: number; onOverview: () => void; onPause: () => void; onAnswer: (answer: "good" | "changed" | "unsure") => void }) {
  const [showHelp, setShowHelp] = useState(false);
  return <div className="screen guide-screen"><header className="guide-topbar"><button className="back-button" onClick={onOverview}><ListChecks size={18} /> View route</button><span>{index + 1} of {total}</span><button className="back-button" onClick={onPause}><Pause size={17} /> Pause</button></header><div className="guide-progress"><span style={{ width: `${((index + 1) / total) * 100}%` }} /></div><main className="guide-card"><div className="guide-area"><MapPin size={15} /> {item.area} · {item.place}</div><div className="guide-plant-icon"><Flower2 size={36} /></div><span className="eyebrow">Check {index + 1}</span><h1>{item.name}</h1><p className="guide-meta">{item.meta}</p><div className="observation-prompt"><span>Take a closer look</span><h2>{item.prompt}</h2><p>{item.detail}</p></div><div className="answer-grid"><button onClick={() => onAnswer("good")}><CheckCircle2 size={23} /><span><strong>Looks good</strong><small>Nothing has changed</small></span></button><button onClick={() => onAnswer("changed")}><Camera size={23} /><span><strong>Something changed</strong><small>Ask Verdant with a photo</small></span></button><button onClick={() => setShowHelp(!showHelp)}><CircleHelp size={23} /><span><strong>I’m not sure</strong><small>Show me what to inspect</small></span></button></div>{showHelp && <div className="inspection-help" role="status"><Sparkles size={18} /><div><strong>Start with the newest leaves.</strong><p>Compare their colour and shape with the older leaves, then look at the soil surface. You do not need to identify a problem—just note anything that seems different.</p></div></div>}</main></div>;
}

export function WalkSummary({ items, onDone, onRestart }: { items: WalkItem[]; onDone: () => void; onRestart: () => void }) {
  const checked = items.filter((item) => item.status === "good").length;
  const skipped = items.filter((item) => item.status === "skipped").length;
  return <div className="screen summary-screen"><div className="summary-check"><Check size={34} /></div><span className="eyebrow">Garden Walk complete</span><h1>Nice work. Your garden is checked.</h1><p>Today’s observations have been added to Activity. Nothing else needs your attention right now.</p><div className="summary-stats"><div><strong>{checked}</strong><span>Plantings checked</span></div><div><strong>{skipped}</strong><span>Skipped for today</span></div><div><strong>Fri</strong><span>Next useful walk</span></div></div><section className="summary-note"><CloudRain size={22} /><div><strong>No watering reminder added</strong><p>Afternoon rain is still likely. Verdant will adjust if the forecast changes.</p></div></section><div className="summary-actions"><button className="primary-button" onClick={onDone}>Return to Today</button><button className="secondary-button" onClick={onRestart}>Review route</button></div></div>;
}
